language: java

jdk:
  - oraclejdk11
  
services:
  - mongodb
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
 
script:
  - ./mvnw clean verify
cache:
  directories:
    - '$HOME/.m2/repository'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
